services:
  - type: web
    name: doctor-appointment-backend
    env: node
    buildCommand: npm install && npm rebuild bcrypt --build-from-source
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 18.x