services:
  - type: web
    name: doctor-appointment-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: PORT
        value: 10000
